mumble-www.go

This /grumble/ configuration makes sure to serve static files right away.
However, this is not necessary. No other configuration matches /grumble/
and we fall back to serving static files.

Remove unnecessary /grumble/ serve configuration

---

hugo/static/css/mumble.css

The left padding is required right now for the logo headline,
but before this change breaks the layout continuity in content.

CSS: Fix headlines indent in content

---

hugo/config.toml

For now, as we have no in-website documentation yet, make the
Documentation menu item link to our documentation wiki.

Menu: Link Documentation menu item to wiki

---

hugo/layouts/partials/footer.html

A copyright notice is not necessary to receive and retain copyright.
A copyright year is typically/originally added so users may see when the
copyright expires.
However, nobody will wait for copyright on our website to expire to make
use of its content.
And if necessary, the source repository retains a history.
I also do not see how the notice could be useful when saving or printing
the website. I doubt that’s a typical use case, and the above
argumentation applies.
I am also wondering if always printing the current year is correct.
Does the copyright start when we distribute/publish, even when the
content does not change?
The notice before this change (footer at the bottom of the page):

Layout: Drop footer copyright notice

---

hugo/content/privacy.md

The text about ads is being removed as we do not serve ads. (We did in
the past on the wiki.)
Add descriptions of our services and what data they transfer, collect
and make available.

Content: Add Privacy Policy

---

hugo/config/_default/menus.toml
hugo/content/documentation/_index.md
hugo/content/documentation/mumble-server/scripting/_index.md
hugo/content/documentation/mumble-server/scripting/ice/_index.md
hugo/content/documentation/mumble-server/scripting/ice/compiling.md
hugo/content/documentation/mumble-server/scripting/ice/glacier2.md
hugo/content/documentation/mumble-server/scripting/ice/php/_index.md
hugo/content/documentation/mumble-server/scripting/ice/php/setup.md
hugo/content/documentation/mumble-server/scripting/ice/server-setup.md

* Add a landing page for documentation
* Add a scripting page
* Migrate Ice wiki documentation
* Split into subpages
* Adjust formatting to markdown
* Drop very obsolete block (also removed from wiki)
* Fix various errors, various improvements
* More consistent and throughout use of markup
This change migrates the Ice documentation. It does not yet improve the layout for documentation, but will allow us to do so with some content and subpages.
For now an aside license and wiki link footer is added. This can probably be improved in the future by adding front matter and rendering it in the layout.

Docs: Add documentation section and migrate Ice documentation

---

.azure-pipelines.yml

The Azure pipelines Microsoft hosted agents have multiple go versions installed.
One of those is installed as a default and prepared.
Fixes our Azure builds failing on the prepare-go step.

CI: Use default go installation

---

hugo/content/sponsors.md

Improvements to the Sponsors page layout.
I think the logos are way too big, jumping into one’s face, diminishing clarity of the text and content.
This PR includes two technically unrelated changes to the same content: Using typographically correct apostrophes and fixing the heading levels.
|  | Before | After this change |
|---|---|---|
| full width | ![image](https://user-images.githubusercontent.com/93181/94860029-c3d18c80-0435-11eb-8ed2-958786436379.png) | ![image](https://user-images.githubusercontent.com/93181/94860063-cfbd4e80-0435-11eb-910b-b8a4121e5b56.png) |
| small width | ![image](https://user-images.githubusercontent.com/93181/94860134-e663a580-0435-11eb-93a0-b26fa991416d.png) | ![image](https://user-images.githubusercontent.com/93181/94860154-eebbe080-0435-11eb-9e23-c305ff8c6 …

Content: Improve sponsors page layout

---

hugo/assets/css/common.scss
hugo/assets/css/layout.scss
hugo/layouts/_default/baseof.html
hugo/layouts/blog/single.html

For headings with an id attribute add anchors that show on hover and are clickable.
They link to the #id hash so clicking them will jump to that headline and update the address bar,
and copying their link will copy a link to that page and heading.
The anchor will show on hover anywhere on the heading (not just to the left of it where the anchor link is).
This also does not break our 1.3.0 release notes blog post which had anchors at the end of them.
The unicode link character could be replaced with an icon. A blue color to match our hyperlinks could be good. We could also change that later though.
This change is especially useful for longer blog posts like release announcements, and will be useful for longer content pages, especially documentation.
Implements #43.

Add heading hover-id-links

---

hugo/assets/css/downloads.scss
hugo/content/downloads.md

This may be worth it even if only Windows works as that is our primary user platform (even moreso those that download from us).
* <https://developer.mozilla.org/en-US/docs/Web/API/Navigator/oscpu>

Downloads: Suggest a download based on the browsing OS

---

hugo/config/_default/menus.toml

The current header links seem to point to a directory or have additional webserver config which causes the server to issue a redirect to the actual page. This introduces an extra RTT of latency for the page load which could be removed by having the links point directly.
Example of the current behavior:
```
$ curl -i https://www.mumble.info/downloads
HTTP/2 301
server: Apache
location: downloads/
accept-ranges: bytes
date: Mon, 01 Feb 2021 20:43:38 GMT
via: 1.1 varnish
age: 368
x-served-by: cache-ewr18153-EWR
x-cache: HIT
x-cache-hits: 1
x-timer: S1612212219.622961,VS0,VE0
strict-transport-security: max-age=300
content-length: 0
```

Config: Update URL paths in menus.toml

---

hugo/content/downloads.md
src/downloads.go

macOS <= 10.12 apparently does not support the new APFS filesystem that
we are using to package the dmg binary. Therefore we are now also
providing a version using the older HFS+ filesystem.
See https://github.com/mumble-voip/mumble/issues/4655

DOWNLOADS: Added HFS+ package for older macOS

---

hugo/config/_default/menus.toml
hugo/content/about.md
hugo/content/contact.md

-Also moves "Sponsors" to the footer menu
The website is missing some general content most websites offer.
It also makes you a bit more trust-worthy and transparent.
Some of it might even be a legal requirement.
Fixes #126 and #98.

Added pages for "Contact" and "About"

---

hugo/content/downloads.md

The script to determine the user's OS throws an exception in some browsers as `navigator.oscpu` is not necessarily set.
```
(index):69 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
at parsePlatform ((index):69)
at getPlatform ((index):90)
at (index):110
```
This PR adds a check to avoid trying to perform string operations on undefined values.

Downloads: Handle undefined navigator attributes

---

hugo/content/downloads.md

As the value is lowercased by `toLowerCase()`, comparing the platform strings with a mixed case string doesn't work as intended. This causes macOS users to not be correctly identified. Not sure how I missed this in my previous PR!

Downloads: Fix case sensitivity in platform names

---

hugo/content/contribute.md

Screenshot:
Noteworthy: The Weblate image is referenced hosted by Weblate. So theoretically they could track our visitors. I think the use (up to date status) outweighs the theoretical privacy concerns though.

Add new translation information to Contribute page

---

hugo/content/contribute.md
hugo/layouts/shortcodes/toc.html

The manually added ToC targets anchors. As a result when updating headlines the ToC must also be updated.
This is error prone.
The resulting ToC list changes slightly in which headlines it displays.
Instead of a selection over three levels deep, the first two headline levels are listed.
This works fine for the content at hand.
---
Screenshot of the ToC before and after:

Use generated Table of Contents on Contribute page

---

hugo/content/blog/2021-03-20-weblate-translation/index.md

This is more than a technical blog post so the News category is applied.
As a result, the "latest News on the home page does not show the snapshot release anymore.

Blog: Add news about migration to Weblate

---

hugo/content/contact.md

This will make it easy for people to join the chat using their preferred Matrix application.
Matrix apps may even bind an handler to the URL on some platforms. I think Element Android does that, so clicking this link will open the chat up in their app of choice.

Add matrix.to link to contact page

---

hugo/content/contribute.md
hugo/content/documentation/developer/positional-audio/create-plugin/_index.md
hugo/content/documentation/developer/positional-audio/create-plugin/guide/index.md

As discussed in https://github.com/mumble-voip/mumble/discussions/5041 IRC is deprecated in favor of Matrix.

Remove remaining references to IRC

---

hugo/content/blog/2021-09-12-mumble-release-candidate1.md
hugo/content/documentation/user/positional-audio/supported-games.md
hugo/content/downloads.md

I have the signed Windows and macOS binaries available. They just have to be uploaded when this goes live.
The first commit in this PR doesn't actually have anything to do with the RC but was something I had to fix in order to work on that. I figured I'll simply smuggle this in here.
TODO:

Release RC1 of Mumble 1.4.0

---

hugo/layouts/documentation/single.html

The documentation lacked a table of content. For starters, I simply added the existing toc.html

Add documentation toc

---

hugo/assets/css/content/_documentation.scss
hugo/assets/css/main.scss
hugo/config.toml
hugo/layouts/documentation/single.html

This adds the button “Edit on GitHub” on single pages in the Mumble documentation.
|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/109021367/208267402-c2aab8bd-bf88-4595-ba9f-165f4a5b8b32.png)|![after](https://user-images.githubusercontent.com/109021367/208267383-0b1c07b6-838b-407d-a4f7-50cacbbbcb18.png)|

Add button “Edit on GitHub”

---

hugo/content/documentation/html-and-css.md

Replaces https://wiki.mumble.info/wiki/Usage_of_HTML_and_CSS_in_Mumble

docs(richtext): Add richtext HTML and CSS notes

---

hugo/content/documentation/developer/channel-viewer-protocol/index.md

Migrated from our Wiki at https://wiki.mumble.info/wiki/Channel_Viewer_Protocol
Dropped dead/404 xsd references
Explicitly declare two x_addr fields because the old docs had two names - x_addrstr and x_addrstring.

docs(cvp): Add Channel Viewer Protocol documentation

---

hugo/content/documentation/developer/positional-audio/create-plugin/guide/index.md
hugo/content/documentation/user/audio-settings/index.md

These relative parent paths worked on hugo version 0.122.0 but not on 0.124.1.
The adjusted paths work on both.

docs: Fix relref paths

---

hugo/content/downloads.md

Davide confirmed we require 2022.
Some more technical context: VC Redist is backwards compatible - 2022 is backwards compatible down to 2015.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
With the 1.5 version, we no longer publish x86, so we drop that redist requirement mention too.

Downloads: Fix required VC redist version reference

---

hugo/content/downloads.md

https://www.flathub.org does not have a valid certificate, www. has to be removed.
So this replaces current https://www.flathub.org/apps/info.mumble.Mumble by https://flathub.org/apps/info.mumble.Mumble

Fix link to Flathub

---

hugo/content/documentation/developer/_index.md

Through https://github.com/mumble-voip/mumble/pull/6623 we migrated our separate network protocol documentation repository into our main project repository docs folder.

Add docs network protocol link
